# Site settings
title: portfolYOU
description: >- # this means to ignore newlines until "baseurl:"
  Always code as if the guy who ends up maintaining your code
  will be a violent psychopath who knows where you live.
baseurl: "/portfolYOU"  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name          : John Doe
  image         : https://bit.ly/2Fqe5kQ
  behance       : your_username
# dribbble      : your_username
  email         : username@domain.com
  facebook      : your_username
  github        : your_username
# gitlab        : your_username
# instagram     : your_username
  linkedin      : your_username
  medium        : your_username
# soundcloud    : your_username
# spotify       : your_username
# stackoverflow : your_user_id
# tumblr        : your_username.tumblr.com
# twitch        : your_username
  twitter       : your_username
# vimeo         : your_username
# youtube       : your_channel_name

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock